# Generated by Django 6.0.3 on 2026-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userinfo_size_alter_userinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='size',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='身高'),
        ),
    ]
