# Generated by Django 6.0.3 on 2026-03-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_userinfo_age_alter_userinfo_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, default=2, verbose_name='年龄'),
        ),
    ]
