# Generated by Django 6.0.3 on 2026-03-25 03:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_userinfo_age_alter_userinfo_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='班级名称')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='size',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='身高'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100, message='年龄不能大于100岁'), django.core.validators.MinValueValidator(0, message='年龄不能小于0岁')], verbose_name='年龄')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.grade', verbose_name='班级ID')),
            ],
        ),
    ]
